controllers:
    resource: ../../src/Controller/*
    type: annotation
    exclude: ../../src/Controller/Api

api:
    resource: ../../src/Controller/Api
    type: annotation
    prefix: '/api'
    name_prefix: 'api_'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
